site_name: poppy-uppsala
nav:
  - General:
    - Introduction: intro.md
    - Pipeline overview: overview.md
    - Output: output_files.md
  - Running Poppy Uppsala:
      - Setup and configuration: setup.md
      - Running poppy-uppsala: run.md # Overwrite some configurations # adapts to what machine is used, overload mosdepth to use
      - Step by step:
          - Poppy GMS:
            - Prealignment: prealignment.md
            - Alignment: alignment.md
            - SNVs and INDELs: snv-indels.md
            - Pindel: pindel.md
          - Uppsala's specific steps:
            - Excel report: excel.md
            - Bamsnap: bamsnap.md
      - References # what should come in there?
  - Known issues: issues.md

theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs/", "workflow/rules/"]
      url_download: "True"
  - mdx_spanner
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - yaml-schema:
      yaml_files:
        - file: "workflow/schemas/config.schema.yaml"
          tag: "CONFIGSCHEMA"
        - file: "workflow/schemas/resources.schema.yaml"
          tag: "RESOURCESSCHEMA"
  - snakemake-rule:
      rule_folders:
        - 'workflow/rules'
      schemas:
        - 'workflow/schemas/rules.schema.yaml'