---
resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "output_files.yaml"

default_container: "{{HYDRAGENETICS_PREFIX}}/common{{CONTAINER_SUFFIX}}1.10.2{{CONTAINER_EXT}}"

modules:
  alignment: v0.5.1
  annotation: v1.0.0
  cnv_sv: "1aa9a68" # v0.5.0
  filtering: v0.3.0
  prealignment: v1.2.0
  qc: v0.4.1
  reports: v0.3.1
  snv_indels_uppsala: v1.1.0

reference:
  fasta: "{{ref_fasta}}"
  fai: "{{ref_fai}}"
  dict: "{{ref_dict}}"
  exon_bed: "{{ref_exon_bed}}"
  design_bed: "{{ref_design_bed}}"
  design_intervals: "{{ref_design_intervals}}"
  design_intervals_gatk_cnv: "{{ref_design_intervals_gatk_cnv}}"
  artifacts: "{{ref_artifacts}}"
  artifacts_pindel: "{{ref_artifacts_pindel}}"
  background: "{{ref_background}}"
  skip_chrs:
    - "chrM"
    - "chr1_KI270706v1_random"
    - "chr1_KI270707v1_random"
    - "chr1_KI270708v1_random"
    - "chr1_KI270709v1_random"
    - "chr1_KI270710v1_random"
    - "chr1_KI270711v1_random"
    - "chr1_KI270712v1_random"
    - "chr1_KI270713v1_random"
    - "chr1_KI270714v1_random"
    - "chr2_KI270715v1_random"
    - "chr2_KI270716v1_random"
    - "chr3_GL000221v1_random"
    - "chr4_GL000008v2_random"
    - "chr5_GL000208v1_random"
    - "chr9_KI270717v1_random"
    - "chr9_KI270718v1_random"
    - "chr9_KI270719v1_random"
    - "chr9_KI270720v1_random"
    - "chr11_KI270721v1_random"
    - "chr14_GL000009v2_random"
    - "chr14_GL000225v1_random"
    - "chr14_KI270722v1_random"
    - "chr14_GL000194v1_random"
    - "chr14_KI270723v1_random"
    - "chr14_KI270724v1_random"
    - "chr14_KI270725v1_random"
    - "chr14_KI270726v1_random"
    - "chr15_KI270727v1_random"
    - "chr16_KI270728v1_random"
    - "chr17_GL000205v2_random"
    - "chr17_KI270729v1_random"
    - "chr17_KI270730v1_random"
    - "chr22_KI270731v1_random"
    - "chr22_KI270732v1_random"
    - "chr22_KI270733v1_random"
    - "chr22_KI270734v1_random"
    - "chr22_KI270735v1_random"
    - "chr22_KI270736v1_random"
    - "chr22_KI270737v1_random"
    - "chr22_KI270738v1_random"
    - "chr22_KI270739v1_random"
    - "chrY_KI270740v1_random"
    - "chrUn_KI270302v1"
    - "chrUn_KI270304v1"
    - "chrUn_KI270303v1"
    - "chrUn_KI270305v1"
    - "chrUn_KI270322v1"
    - "chrUn_KI270320v1"
    - "chrUn_KI270310v1"
    - "chrUn_KI270316v1"
    - "chrUn_KI270315v1"
    - "chrUn_KI270312v1"
    - "chrUn_KI270311v1"
    - "chrUn_KI270317v1"
    - "chrUn_KI270412v1"
    - "chrUn_KI270411v1"
    - "chrUn_KI270414v1"
    - "chrUn_KI270419v1"
    - "chrUn_KI270418v1"
    - "chrUn_KI270420v1"
    - "chrUn_KI270424v1"
    - "chrUn_KI270417v1"
    - "chrUn_KI270422v1"
    - "chrUn_KI270423v1"
    - "chrUn_KI270425v1"
    - "chrUn_KI270429v1"
    - "chrUn_KI270442v1"
    - "chrUn_KI270466v1"
    - "chrUn_KI270465v1"
    - "chrUn_KI270467v1"
    - "chrUn_KI270435v1"
    - "chrUn_KI270438v1"
    - "chrUn_KI270468v1"
    - "chrUn_KI270510v1"
    - "chrUn_KI270509v1"
    - "chrUn_KI270518v1"
    - "chrUn_KI270508v1"
    - "chrUn_KI270516v1"
    - "chrUn_KI270512v1"
    - "chrUn_KI270519v1"
    - "chrUn_KI270522v1"
    - "chrUn_KI270511v1"
    - "chrUn_KI270515v1"
    - "chrUn_KI270507v1"
    - "chrUn_KI270517v1"
    - "chrUn_KI270529v1"
    - "chrUn_KI270528v1"
    - "chrUn_KI270530v1"
    - "chrUn_KI270539v1"
    - "chrUn_KI270538v1"
    - "chrUn_KI270544v1"
    - "chrUn_KI270548v1"
    - "chrUn_KI270583v1"
    - "chrUn_KI270587v1"
    - "chrUn_KI270580v1"
    - "chrUn_KI270581v1"
    - "chrUn_KI270579v1"
    - "chrUn_KI270589v1"
    - "chrUn_KI270590v1"
    - "chrUn_KI270584v1"
    - "chrUn_KI270582v1"
    - "chrUn_KI270588v1"
    - "chrUn_KI270593v1"
    - "chrUn_KI270591v1"
    - "chrUn_KI270330v1"
    - "chrUn_KI270329v1"
    - "chrUn_KI270334v1"
    - "chrUn_KI270333v1"
    - "chrUn_KI270335v1"
    - "chrUn_KI270338v1"
    - "chrUn_KI270340v1"
    - "chrUn_KI270336v1"
    - "chrUn_KI270337v1"
    - "chrUn_KI270363v1"
    - "chrUn_KI270364v1"
    - "chrUn_KI270362v1"
    - "chrUn_KI270366v1"
    - "chrUn_KI270378v1"
    - "chrUn_KI270379v1"
    - "chrUn_KI270389v1"
    - "chrUn_KI270390v1"
    - "chrUn_KI270387v1"
    - "chrUn_KI270395v1"
    - "chrUn_KI270396v1"
    - "chrUn_KI270388v1"
    - "chrUn_KI270394v1"
    - "chrUn_KI270386v1"
    - "chrUn_KI270391v1"
    - "chrUn_KI270383v1"
    - "chrUn_KI270393v1"
    - "chrUn_KI270384v1"
    - "chrUn_KI270392v1"
    - "chrUn_KI270381v1"
    - "chrUn_KI270385v1"
    - "chrUn_KI270382v1"
    - "chrUn_KI270376v1"
    - "chrUn_KI270374v1"
    - "chrUn_KI270372v1"
    - "chrUn_KI270373v1"
    - "chrUn_KI270375v1"
    - "chrUn_KI270371v1"
    - "chrUn_KI270448v1"
    - "chrUn_KI270521v1"
    - "chrUn_GL000195v1"
    - "chrUn_GL000219v1"
    - "chrUn_GL000220v1"
    - "chrUn_GL000224v1"
    - "chrUn_KI270741v1"
    - "chrUn_GL000226v1"
    - "chrUn_GL000213v1"
    - "chrUn_KI270743v1"
    - "chrUn_KI270744v1"
    - "chrUn_KI270745v1"
    - "chrUn_KI270746v1"
    - "chrUn_KI270747v1"
    - "chrUn_KI270748v1"
    - "chrUn_KI270749v1"
    - "chrUn_KI270750v1"
    - "chrUn_KI270751v1"
    - "chrUn_KI270752v1"
    - "chrUn_KI270753v1"
    - "chrUn_KI270754v1"
    - "chrUn_KI270755v1"
    - "chrUn_KI270756v1"
    - "chrUn_KI270757v1"
    - "chrUn_GL000214v1"
    - "chrUn_KI270742v1"
    - "chrUn_GL000216v2"
    - "chrUn_GL000218v1"
    - "chrEBV"

annotate_cnv:
  cnv_genes: "{{ref_annotate_cnv_genes}}"

bamsnap:
  extra: " -coverage_vaf 0.05 -show_soft_clipped -read_thickness 2 -read_gap_height 1 "
  container: "{{HYDRAGENETICS_PREFIX}}/bamsnap{{CONTAINER_SUFFIX}}0.2.19{{CONTAINER_EXT}}"

bamsnap_downsample_bam:
  container: "{{HYDRAGENETICS_PREFIX}}/common{{CONTAINER_SUFFIX}}3.1.1.2{{CONTAINER_EXT}}"
  max_reads: 6000000

bcbio_variation_recall_ensemble:
  container: "{{HYDRAGENETICS_PREFIX}}/bcbio-vc{{CONTAINER_SUFFIX}}0.2.6{{CONTAINER_EXT}}"
  callers:
    - gatk_mutect2
    - vardict

bcftools_annotate:
  annotation_db: "{{ref_bcftools_annotate_db}}"

bcftools_concat_vcfs:
  extra: " -a "

bcftools_filter_include_region:
  cll: "{{ref_cll_genes}}"
  myeloid: "{{ref_myeloid_genes}}"
  hotspot: "{{ref_hotspot_genes}}"

bwa_mem:
  amb: "{{ref_bwa_amb}}"
  ann: "{{ref_bwa_ann}}"
  bwt: "{{ref_bwa_bwt}}"
  pac: "{{ref_bwa_pac}}"
  sa: "{{ref_bwa_sa}}"
  container: "{{HYDRAGENETICS_PREFIX}}/bwa_mem{{CONTAINER_SUFFIX}}0.7.17{{CONTAINER_EXT}}"

cnv_html_report:
  cytobands: true
  show_table: true

cnvkit_batch:
  normal_reference: "{{ref_cnvkit_pon}}"
  method: hybrid
  container: "{{HYDRAGENETICS_PREFIX}}/cnvkit{{CONTAINER_SUFFIX}}0.9.9{{CONTAINER_EXT}}"

cnvkit_call:
  container: "{{HYDRAGENETICS_PREFIX}}/cnvkit{{CONTAINER_SUFFIX}}0.9.9{{CONTAINER_EXT}}"

cnvkit_vcf:
  hom_del_limit: 0.47
  het_del_limit: 1.68
  dup_limit: 2.3
  container: "{{HYDRAGENETICS_PREFIX}}/cnvkit{{CONTAINER_SUFFIX}}0.9.9{{CONTAINER_EXT}}"

fastp_pe:
  container: "{{HYDRAGENETICS_PREFIX}}/fastp{{CONTAINER_SUFFIX}}0.20.1{{CONTAINER_EXT}}"

fastqc:
  container: "{{HYDRAGENETICS_PREFIX}}/fastqc{{CONTAINER_SUFFIX}}0.11.9{{CONTAINER_EXT}}"

filter_vcf:
  sample_name_regex: ^([A-Za-z0-9-]+_[NRT]\{1\})$
  germline: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_germline.yaml"
  somatic: "{{POPPY_UU_HOME}}/config/filters/config_soft_filter_somatic.yaml"
  somatic_hard: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_somatic.yaml"
  pindel: "{{POPPY_UU_HOME}}/config/filters/config_soft_filter_pindel.yaml"
  cnv_hard_filter: "{{POPPY_UU_HOME}}/config/filters/config_hard_filter_cnv.yaml"

gatk_collect_allelic_counts:
  SNP_interval: "{{ref_gatk_snp_interval}}"
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.1.9.0{{CONTAINER_EXT}}"

gatk_denoise_read_counts:
  normal_reference: "{{ref_gatk_pon}}"
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.1.9.0{{CONTAINER_EXT}}"

gatk_model_segments:
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.1.9.0{{CONTAINER_EXT}}"

gatk_mutect2:
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.1.9.0{{CONTAINER_EXT}}"

gatk_mutect2_filter:
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.1.9.0{{CONTAINER_EXT}}"

gatk_mutect2_gvcf:
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.1.9.0{{CONTAINER_EXT}}"

gatk_mutect2_merge_stats:
  container: "{{HYDRAGENETICS_PREFIX}}/gatk4{{CONTAINER_SUFFIX}}4.1.9.0{{CONTAINER_EXT}}"

merge_af_complex_variants:
  merge_method: "sum"

merge_cnv_json:
  cytobands: "{{POPPY_UU_HOME}}/config/cytoBand.hg38.txt"
  annotations:
    - "{{ref_annotate_cnv_genes}}"
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.vcf.gz
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.filter.cnv_hard_filter.vcf.gz
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.vcf.gz

mosdepth_bed:
  container: "{{HYDRAGENETICS_PREFIX}}/mosdepth{{CONTAINER_SUFFIX}}0.3.2{{CONTAINER_EXT}}"

multiqc:
  container: "{{HYDRAGENETICS_PREFIX}}/multiqc{{CONTAINER_SUFFIX}}1.21{{CONTAINER_EXT}}"
  reports:
    DNA:
      config: "{{POPPY_UU_HOME}}/config/config_multiqc.yaml"
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastp.json"
        - "qc/mosdepth_bed_coding/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed_coding/{sample}_{type}.per-base.bed.gz"
        - "qc/mosdepth_bed_coding/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed_coding/{sample}_{type}.regions.bed.gz"
        - "qc/mosdepth_bed_coding/{sample}_{type}.thresholds.bed.gz"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "versions/update_poppy.temp"

picard_collect_alignment_summary_metrics:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.0{{CONTAINER_EXT}}"

picard_collect_duplication_metrics:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.0{{CONTAINER_EXT}}"

picard_collect_gc_bias_metrics:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.0{{CONTAINER_EXT}}"

picard_collect_hs_metrics:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.0{{CONTAINER_EXT}}"

picard_collect_insert_size_metrics:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.0{{CONTAINER_EXT}}"

picard_mark_duplicates:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.0{{CONTAINER_EXT}}"

pindel_call:
  extra: "-x 2 -B 60"
  include_bed: "{{ref_pindel_include_bed}}"
  container: "{{HYDRAGENETICS_PREFIX}}/pindel{{CONTAINER_SUFFIX}}0.2.5b9{{CONTAINER_EXT}}"

pindel_update_vcf:
  container: "{{HYDRAGENETICS_PREFIX}}/picard{{CONTAINER_SUFFIX}}2.25.4{{CONTAINER_EXT}}"

pindel2vcf:
  extra: "-e 10 -mc 10 -is 5 -he 0.01 -G"
  refname: "GCA_000001405.15_GRCh38_no_alt"
  refdate: "2022"
  container: "{{HYDRAGENETICS_PREFIX}}/pindel{{CONTAINER_SUFFIX}}0.2.5b9{{CONTAINER_EXT}}"

purecn:
  genome: GRCh38
  normaldb: "{{ref_purecn_normaldb}}"
  intervals: "{{ref_purecn_intervals}}"
  mapping_bias_file: "{{ref_purecn_mapping_bias_file}}"
  container: "{{HYDRAGENETICS_PREFIX}}/purecn{{CONTAINER_SUFFIX}}2.2.0{{CONTAINER_EXT}}"

purecn_coverage:
  intervals: "{{ref_purecn_intervals}}"
  container: "{{HYDRAGENETICS_PREFIX}}/purecn{{CONTAINER_SUFFIX}}2.2.0{{CONTAINER_EXT}}"

results_report_xlsx:
  wanted_transcripts: "{{ref_wanted_transcripts}}"

svdb_merge:
  tc_method:
    - name: purecn
      cnv_caller:
        - cnvkit
        - gatk
    - name: pathology
      cnv_caller:
        - cnvkit
        - gatk
  container: "{{HYDRAGENETICS_PREFIX}}/svdb{{CONTAINER_SUFFIX}}2.6.0{{CONTAINER_EXT}}"

svdb_query:
  db_string: "--db {{ref_svdb_db}} --out_frq Normal_AF --out_occ Normal_{{platform}}"
  container: "{{HYDRAGENETICS_PREFIX}}/svdb{{CONTAINER_SUFFIX}}2.6.0{{CONTAINER_EXT}}"

vardict:
  container: "{{HYDRAGENETICS_PREFIX}}/vardict{{CONTAINER_SUFFIX}}1.8.3{{CONTAINER_EXT}}"
  extra: " -Q 1 --nosv "
  bed_columns: "-c 1 -S 2 -E 3"

vep:
  vep_cache: "{{ref_vep_cache}}"
  container: "{{HYDRAGENETICS_PREFIX}}/vep{{CONTAINER_SUFFIX}}111.0{{CONTAINER_EXT}}"
  mode: "--offline --cache --merged "
  extra: " --assembly GRCh38 --check_existing --pick --variant_class --everything --pick_order mane_select,mane_plus_clinical,canonical,biotype,rank,appris,tsl,ccds,length,ensembl,refseq"

vt_decompose:
  container: "{{HYDRAGENETICS_PREFIX}}/vt{{CONTAINER_SUFFIX}}2015.11.10{{CONTAINER_EXT}}"

vt_normalize:
  container: "{{HYDRAGENETICS_PREFIX}}/vt{{CONTAINER_SUFFIX}}2015.11.10{{CONTAINER_EXT}}"

# rindels:
#   bin: "bin/rindels"
#   extra: "--ont"

# rs_qc:
#   bin: "bin/rs-qc"

# aligner: "bwa"
