---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "output_files.yaml"

reference:
  fasta: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta"
  fai: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.fai"
  design_bed: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Design/Twist_myeloid_TE-91316667_hg38.240122.bed"
  design_intervals: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Design/Twist_myeloid_TE-91316667_hg38.240122.interval_list" #hsmetrics
  design_intervals_gatk_cnv: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Design/Twist_myeloid_TE-91316667_hg38.240122.interval_list" #Correct
  artifacts: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Runfolders/ReferencePools/240205/reference_files/artifact_panel.tsv"
  skip_chrs:
  - "chrM"

annotate_cnv:
  cnv_genes: "/data/ref_genomes/GRCh38/gene_lists/hg38_CNA.bed"

bwa_mem:
  amb: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.amb"
  ann: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.ann"
  bwt: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.bwt"
  pac: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.pac"
  sa: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.sa"

cnv_html_report:
  cytobands: true
  show_table: true

cnvkit_batch:
  normal_reference: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Runfolders/ReferencePools/240205/reference_files/cnvkit.PoN.cnn"
  method: hybrid

filter_vcf:
  germline: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_hard_filter_germline.yaml"
  somatic: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_soft_filter_somatic.yaml"
  pindel: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_soft_filter_pindel.yaml"
  cnv_hard_filter_amp: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_hard_filter_cnv_amp.yaml"
  cnv_hard_filter_loh: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_hard_filter_cnv_loh.yaml"

merge_cnv_json:
  cytobands: "cytoBand.hg38.txt"
  annotations:
    - "/data/ref_genomes/GRCh38/gene_lists/hg38_CNA.bed"
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.vcf.gz
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.filter.cnv_hard_filter_amp.vcf.gz
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.vcf.gz

# mosdepth_bed:
#   thresholds: "100,200,1000"

multiqc:
  config: "config/multiqc.yaml"

gatk_collect_allelic_counts:
  SNP_interval: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Design/Twist_myeloid_cnv100.240208.interval_list" 

gatk_denoise_read_counts:
  normal_reference: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Runfolders/ReferencePools/240205/reference_files/gatk.PoN.hdf5"

pindel_call:
  extra: "-x 2 -B 60" #x och B?
  include_bed: "/data/ref_genomes/GRCh38/gene_lists/aml_pindel_38.bed" # needs to be updated

pindel2vcf:
  extra: "-e 10 -mc 10 -is 5 -he 0.01 -G" # num reads support
  refname: "GRCh38_p14"
  refdate: "2022"

svdb_query:
  db_string: "--db /projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Runfolders/ReferencePools/240205/reference_files/svdb_cnv.vcf --out_frq Normal_AF --out_occ Normal_240205"

vep:
  vep_cache: "/data/ref_genomes/VEP"
