---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "output_files.yaml"

reference:
  fasta: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta"
  fai: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.fai"
  design_bed: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Design/Twist_myeloid_TE-91316667_hg38.240122.bed"
  design_intervals: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Design/Twist_myeloid_TE-91316667_hg38.240122.intervals" #hsmetrics
  design_intervals_gatk_cnv: ""
  skip_chrs:
  - "chrM"

annotate_cnv:
  cnv_genes: "/data/ref_genomes/GRCh38/gene_lists/hg38_CNA.bed"

bwa_mem:
  amb: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.amb"
  ann: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.ann"
  bwt: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.bwt"
  pac: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.pac"
  sa: "/data/ref_genomes/GRCh38_p14/homo_sapiens.fasta.sa"

cnv_html_report:
  cytobands: true
  show_table: true

cnvkit_batch:
  normal_reference: "FILL_ME_IN.cnn"
  method: hybrid

filter_vcf:
  germline: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_hard_filter_germline.yaml"
  somatic: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_soft_filter_somatic.yaml"
  cnv_hard_filter_amp: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_hard_filter_cnv_amp.yaml"
  cnv_hard_filter_loh: "/projects/wp2/nobackup/CGU_2023_30_TM_new_panel/Bin/poppy/config/config_hard_filter_cnv_loh.yaml"

merge_cnv_json:
  cytobands: workflow.source_path("../../config/cytoBand.hg38.txt")
  annotations:
    - config/cnv_genes.hg19.bed
  germline_vcf: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.filter.germline.vcf.gz
  filtered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.filter.cnv_hard_filter_amp.vcf.gz
  unfiltered_cnv_vcfs:
    - cnv_sv/svdb_query/{sample}_{type}.{tc_method}.svdb_query.annotate_cnv.cnv_genes.vcf.gz

mosdepth_bed:
  thresholds: ""

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  config: "config/multiqc.yaml"

gatk_collect_allelic_counts:
  SNP_interval: "FILL_ME_IN"

gatk_denoise_read_counts:
  normal_reference: "FILL_ME_IN.hdf5"

pindel_call:
  extra: "-x 2 -B 60" #x och B?
  include_bed: "/data/ref_genomes/GRCh38/gene_lists/aml_pindel_38.bed" # needs to be updated

pindel2vcf:
  extra: "-e 10 -mc 10 -is 5 -he 0.01 -G" # num reads support
  refname: "GRCh38_p14"
  refdate: "2022"

svdb_query:
  db_string: "FILL_ME_IN"

vardict:
  container: "docker://hydragenetics/vardict:1.8.3"
  bed_columns: "-c 1 -S 2 -E 3"

vep:
  container: docker://hydragenetics/vep:109
  vep_cache: "/data/ref_genomes/VEP"
  mode: --offline --cache
  extra: " --assembly GRCh38 --check_existing --pick --variant_class --everything"
