samples: samples_references.tsv
units: units_references.tsv
resources_references: config/resources_references.yaml
output: output_files_references.yaml

reference:
  mappability: "/data/ref_genomes/GRCh38/cnvkit/access-10kb.mm10.bed"

purecn_interval_file:
  genome: "GRCh38"

