directory: ./results
files:
  - name: Alignment BAM file
    input: alignment/samtools_merge_bam/{sample}_{type}.bam
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.bam"

  - name: Alignment BAM file index
    input: alignment/samtools_merge_bam/{sample}_{type}.bam.bai
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.bam.bai"

  - name: MultiQC
    input: qc/multiqc/multiqc_DNA.html
    output: "multiqc_{sequenceid}.html"

  - name: SNVs and indels VCF file
    input: "snv_indels/bcftools_concat/{sample}_{type}.filter.somatic.vcf.gz"
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.snvs-indels.vcf.gz"

  - name: SVDB CNV VCF file # ofiltrerad
    input: cnv_sv/svdb_query/{sample}_{type}.pathology.svdb_query.vcf.gz
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.pathology.svdb_query.vcf.gz"

  - name: xlsx report
    input: reports/xlsx/{sample}_{type}.xlsx
    output: "{sample}_{sequenceid}/reports/{sample}_{type}_{sequenceid}.report.xlsx"
  
  - name: CNV HTML report, pathology TC
    input: reports/cnv_html_report/{sample}_{type}.pathology.cnv_report.html
    output: "{sample}_{sequenceid}/reports/{sample}_{type}_{sequenceid}.pathology.cnv_report.html"

  - name: bamsnap
    input: bamsnap/bamsnap/{sample}_{type}/
    output: "{sample}_{sequenceid}/reports/{sample}_{type}_{sequenceid}_bamsnap/"
