directory: ./results
files:
  - name: Alignment BAM file
    input: alignment/samtools_merge_bam/{sample}_{type}.bam
    output: bam/{sample}_{type}.bam

  - name: Alignment BAM file index
    input: null
    output: bam/{sample}_{type}.bam.bai

  - name: MultiQC
    input: qc/multiqc/multiqc_DNA.html
    output: qc/multiqc_DNA.html

  - name: SNV ensemble soft filtered VCF file
    input: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.artifact_annotated.filter.somatic.vcf.gz
    output: vcf/{sample}_{type}.filter.somatic.vcf.gz

  - name: Pindel VCF file # add softfilter?
    input: cnv_sv/pindel_vcf/{sample}_{type}.no_tc.vep_annotated.filtered.pindel.vcf.gz
    output: vcf/{sample}_{type}.pindel.vep_annotated.vcf.gz

  - name: SVDB CNV VCF file
    input: cnv_sv/svdb_query/{sample}_{type}.pathology.svdb_query.vcf.gz
    output: cnv/{sample}/{sample}_{type}.pathology.svdb_query.vcf.gz

  - name: CNV HTML report
    input: reports/cnv_html_report/{sample}_{type}.pathology.cnv_report.html
    output: cnv/{sample}/{sample}_{type}.pathology.cnv_report.html

  - name: xlsx report
    input: results_report/xlsx/{sample}_{type}.xlsx
    output: snv_indels/{sample}_{type}.report.xlsx