directory: ./results
files:
  - name: Alignment BAM file
    input: alignment/samtools_merge_bam/{sample}_{type}.bam
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.bam"

  - name: Alignment BAM file index
    input: null
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.bam.bai"

  - name: MultiQC
    input: qc/multiqc/multiqc_DNA.html
    output: "{sequenceid}_MultiQC_DNA.html"

  - name: SNV ensemble soft filtered VCF file
    input: snv_indels/bcbio_variation_recall_ensemble/{sample}_{type}.ensembled.vep_annotated.artifact_annotated.filter.somatic.vcf.gz
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.filter.somatic.vcf.gz"

  - name: Pindel VCF file # merga med vanliga vcfs
    input: cnv_sv/pindel_vcf/{sample}_{type}.no_tc.vep_annotated.vcf.gz
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.pindel.vep_annotated.vcf.gz"

  - name: SVDB CNV VCF file # ofiltrerad
    input: cnv_sv/svdb_query/{sample}_{type}.pathology.svdb_query.vcf.gz
    output: "{sample}_{sequenceid}/data/{sample}_{type}_{sequenceid}.pathology.svdb_query.vcf.gz"

  - name: xlsx report
    input: reports/xlsx/{sample}_{type}.xlsx
    output: "{sample}_{sequenceid}/reports/{sample}_{type}_{sequenceid}.report.xlsx"
  
  - name: CNV HTML report, pathology TC
    input: reports/cnv_html_report/{sample}_{type}.pathology.cnv_report.html
    output: "{sample}_{sequenceid}/reports/{sample}_{type}_{sequenceid}.pathology.cnv_report.html"

  - name: CNV HTML report, purecn TC
    input: reports/cnv_html_report/{sample}_{type}.purecn.cnv_report.html
    output: "{sample}_{sequenceid}/reports/{sample}_{type}_{sequenceid}.purecn.cnv_report.html"

  - name: bamsnap
    input: bamsnap/bamsnap/{sample}_{type}/
    output: "{sample}_{sequenceid}/reports/{sample}_{type}_{sequenceid}_bamsnap/"