name: Snakemake dry run

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  snakemake-dry-run:
    name: Run snakemake dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: snakemake dry run
        working-directory: .tests/integration
        run: |
          snakemake -n -s ../../workflow/Snakefile --configfiles ../../config/config_uppsala_nextseq.yaml config/config.yaml --config POPPY_HOME=../.. POPPY_UU_HOME=../.. sequenceid="dry_run" poppy_version="v0.2.0"
